# Generated by Django 4.0.1 on 2022-01-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0002_alter_expenses_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='Employee',
            field=models.CharField(default='Ben', max_length=100),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='Manager_Comment',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
