# Generated by Django 4.0.1 on 2022-01-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0003_alter_expenses_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='Reason',
            field=models.CharField(choices=[('FO', 'Food'), ('MI', 'Mileage'), ('EQ', 'Equipment'), ('OT', 'Other')], default='Other', max_length=2),
        ),
    ]
