# Generated by Django 4.0.1 on 2022-01-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0004_alter_expenses_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='Manager_Comment',
            field=models.TextField(default='0', max_length=500),
        ),
    ]
