# Generated by Django 4.0.1 on 2022-01-29 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense_app', '0017_alter_expense_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='evidence',
            new_name='information',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='reason',
        ),
        migrations.AddField(
            model_name='expense',
            name='catagory',
            field=models.CharField(choices=[('SU', 'Subsistence'), ('MI', 'Mileage'), ('En', 'Entertainment'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='expense',
            name='employee',
            field=models.ForeignKey(default=1883396374080, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
