# Generated by Django 4.0.1 on 2022-02-02 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense_app', '0021_alter_expense_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('EU', 'Euro'), ('GB', 'Pound Sterling'), ('US', 'US Dollar'), ('SG', 'Singaporean Dollar'), ('AU', 'Australian Dollar'), ('CH', 'Swiss Franc'), ('HK', 'Hong Kong Dollar')], default='GB', max_length=2),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_date',
            field=models.TextField(default='000000', max_length=6),
        ),
        migrations.AlterField(
            model_name='expense',
            name='employee',
            field=models.ForeignKey(default=1973852422976, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('AP', 'Approved'), ('RE', 'Rejected'), ('DR', 'Draft'), ('PE', 'Pending')], default='PE', max_length=2),
        ),
    ]
