# Generated by Django 4.0.1 on 2022-02-04 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense_app', '0039_alter_expense_employee_alter_expense_persons_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='catagory',
            field=models.CharField(choices=[('AC', 'Accommodation'), ('CE', 'Client entertainment (Incl VAT)'), ('FL', 'Flights'), ('MI', 'Mileage'), ('OH', 'Other'), ('OT', 'Other travel'), ('SE', 'Staff entertainment'), ('SU', 'Subsistence')], default='OH', max_length=2),
        ),
        migrations.AlterField(
            model_name='expense',
            name='employee',
            field=models.ForeignKey(default=1655081444352, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='information',
            field=models.TextField(max_length=500),
        ),
    ]
