# Generated by Django 4.0.2 on 2022-02-06 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense_app', '0042_alter_expense_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='document',
            field=models.FileField(default=' ', upload_to=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='employee',
            field=models.ForeignKey(default=4570737600, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
