# Generated by Django 4.0.1 on 2022-02-12 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0003_alter_expense_employee'),
        ('expense_app', '0048_alter_expense_employee'),
    ]

    operations = [
    ]
