# Generated by Django 4.0.1 on 2022-02-12 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense_app', '0049_merge_20220212_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='manager',
            field=models.ForeignKey(default=1, limit_choices_to={'groups__name': 'Manager'}, on_delete=django.db.models.deletion.PROTECT, related_name='manager', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='employee',
            field=models.ForeignKey(default=2555311118816, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
