# Generated by Django 4.0.1 on 2022-02-12 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense_app', '0053_alter_expense_employee_alter_expense_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='document',
            field=models.FileField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='employee',
            field=models.ForeignKey(default=1819693266640, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='manager',
            field=models.ForeignKey(default=1819693266640, limit_choices_to={'groups__name': 'Manager'}, on_delete=django.db.models.deletion.PROTECT, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='manager_comment',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
