# Generated by Django 4.0.1 on 2022-01-22 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(auto_now=True)),
                ('Employee', models.CharField(max_length=100)),
                ('Expense_Amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('Reason', models.CharField(choices=[('FO', 'Food'), ('MI', 'Milage'), ('EQ', 'Equipment'), ('OT', 'Other')], default='Other', max_length=2)),
                ('Evidence', models.TextField(max_length=500)),
                ('Status', models.CharField(choices=[('AP', 'Approved'), ('RE', 'Rejected'), ('DR', 'Draft'), ('PE', 'Pending')], default='Pending', max_length=2)),
                ('Manager_Comment', models.TextField(max_length=500)),
            ],
        ),
    ]
