# Generated by Django 4.0.1 on 2022-01-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0005_alter_expenses_manager_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['time']},
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='Employee',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='Evidence',
            new_name='evidence',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='Expense_Amount',
            new_name='expense_Amount',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='Manager_Comment',
            new_name='manager_Comment',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='Reason',
            new_name='reason',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='Time',
            new_name='time',
        ),
    ]
