# Generated by Django 4.0.1 on 2022-01-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0009_alter_expense_reason_alter_expense_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='manager_comment',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
