# Generated by Django 4.0.1 on 2022-01-23 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0010_alter_expense_manager_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expense_Amount',
            new_name='expense_amount',
        ),
    ]
