# Generated by Django 4.0.1 on 2022-01-24 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0012_alter_expense_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='employee',
        ),
    ]
